# Generated by Django 2.2.5 on 2020-12-07 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Спільна збірка', max_length=150, unique=True, verbose_name='Назва категорії')),
                ('description', models.TextField(default='(Пусто)', max_length=5000, verbose_name='Опис')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(default='Невизначено', max_length=150, unique=True, verbose_name='Назва датасету')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, verbose_name="Ім'я користувача")),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='', max_length=150, verbose_name='Пароль')),
                ('photo', models.CharField(default='', max_length=150, verbose_name='Аватарка')),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_id', models.PositiveIntegerField()),
                ('tag', models.TextField(default='(Не заданий)', max_length=5000, verbose_name='Теги')),
                ('description', models.TextField(default='(Не заданий)', max_length=5000, verbose_name='Опис')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Datafile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datafile_id', models.PositiveIntegerField()),
                ('path', models.TextField(default='/static/main/datafile...', max_length=150, verbose_name='Шлях')),
                ('mimeType', models.CharField(max_length=150, verbose_name='Тип файлу')),
                ('guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.PositiveIntegerField()),
                ('body', models.TextField(default='', max_length=5000, verbose_name='Коментар')),
                ('GUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Dataset')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.PositiveIntegerField()),
                ('permission', models.TextField(default='Переглядати файли даних', max_length=5000, verbose_name='Дозволи')),
                ('name', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='newapp.User')),
            ],
        ),
    ]
