@startuml
skinparam ArchimateBackgroundColor #ffffff
skinparam	shadowing false
skinparam Note {
	BackgroundColor #f85658
	FontColor #ffffff
}


start
|Адміністратор|
: Обирає модератора;
: Натискає кнопку "Видалити модератора";

|Система|

: Надсилає форму;
: Очікує підтвердження; 

|Адміністратор|
: Вводити інформацію про модератора; 
: Підтверджує операцію;

|Система|
: Видаляє модератора; 
note right

	Можлива EX 02ADMIN

end note

|Адміністратор|

: Отримує повідомлення, що модератор видалений;

stop;


@enduml
