@startuml
skinparam ArchimateBackgroundColor #ffffff
skinparam	shadowing false
skinparam Note {
	BackgroundColor #f85658
	FontColor #ffffff
}

left header
<font color=000 size=18><b>Package:</b> Admin

<font color=000 size=16><b>ID:</b> UC_1.1
<font color=000 size=16><b>Назва:</b> Додавання нового модератора.
<font color=000 size=16><b>Учасники:</b> Адміністратор, система.
<font color=000 size=16><b>Передумови:</b> Адміністратор ввійшов в систему.
<font color=000 size=16><b>Результат:</b> Доданий новий модератор.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EX 01ADMIN: Модератор з таким іменем вже існує в системі

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Адміністратор|
start
: Натискає кнопку "Додати модератора";

: Вводить дані нового модератора;


|Система|

: Вносить відповідні записи до бази данних;

note right

	Можлива EX_01

end note

|Адміністратор|

: З відповіді БД додає нового модератора;

stop;

right footer


Robin ODMS
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
