@startuml

    left header
        <font color=000 size=16><b>ID:</b> UC_12.1
        <font color=000 size=16><b>Назва:</b> Пошук наборів даних
        <font color=000 size=16><b>Учасники:</b> Користувач, Система
        <font color=000 size=16><b>Передумови:</b> Відсутні
        <font color=000 size=16><b>Результат:</b> Список наборів даних, які відповідають запиту
        <font color=000 size=16><b>Виключні ситуації:</b>
        <font color=000 size=16> EX_12.1.1 По даному запиту набір даних не знайдено
        
        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header
    
    |Користувач|
        start
        : Натискає на кнопку "Набори даних";
        
    |Система|
        : Надає список всіх наборів даних та фільтри для пошуку;

    |Користувач|
        : Вибирає потрібні фільтри та/або використовує поле пошуку;
        
    |Система|
        : Обробляє запит;
        
        note right #ffaaaa
        <b> Можливо
        <b> EX_12.1.1
        end note
        
		: Надає список наборів даних, які відповідають запиту;
		
    |Користувач|
        stop;
    
@enduml
