@startuml
skinparam ArchimateBackgroundColor #ffffff
skinparam	shadowing false
skinparam Note {
	BackgroundColor #f85658
	FontColor #ffffff
}



|Адміністратор|
start
: Натискає 'Налаштування набору даних';

|Система|
: Відкриває налаштування;

|Адміністратор|
: Вводить дані про модератора;
: Натискає кнопку "додати модератора";

|Система|
: Опрацьовує запит;
note right

	Можлива EX 03ADMIN
	Можлива EX 04ADMIN

end note
: Надає вибраному модератору права на редагування;

|Адміністратор|

: Отримує повідомлення, що права надані;

stop;


@enduml
