@startuml
skinparam ArchimateBackgroundColor #ffffff
skinparam	shadowing false
skinparam Note {
	BackgroundColor #f85658
	FontColor #ffffff
}

|Адміністратор|
start
: Обирає категорію, яку потрібно видалити;
: Натискає кнопку "видалити категорію";

|Система|

: Видаляє категорію;

|Адміністратор|

: Отримує повідомленн, що категорія видалена;

stop;


@enduml
