@startuml
skinparam ArchimateBackgroundColor #ffffff
skinparam	shadowing false
skinparam Note {
	BackgroundColor #f85658
	FontColor #ffffff
}



|Адміністратор|
start
: Натискає кнопку "Створити нову категорію";

|Система|
: Повертає форму; 

|Адміністратор|
: Вводить назву категорії;

|Система|
: Додає каьегорію;

note right

	Можлива EX 05ADMIN

end note

|Адміністратор|

: Отримує повідомлення, що категорію додано;

stop;


@enduml
