@startuml
skinparam ArchimateBackgroundColor #ffffff
skinparam	shadowing false
skinparam Note {
	BackgroundColor #f85658
	FontColor #ffffff
}



|Адміністратор|
start
: Адміністратор обирає набір даних;
: Натискає кнопку "Видалити набір даних";

|Система|

: Видаляє набір даних;

|Адміністратор|

: Отримує повідомлення, що набір даних видалено;

stop;


@enduml
