@startuml
skinparam ArchimateBackgroundColor #ffffff
skinparam	shadowing false
skinparam Note {
	BackgroundColor #f85658
	FontColor #ffffff
}


|Адміністратор|
start
: Адміністратор обирає назву для набору даних;
: Натискає кнопку "Створити новий набір даних";

|Система|

: Створює новий набір даних;
note right

	Можлива EX 08ADMIN

end note

|Адміністратор|

: Отримує повідомлення, що набір даних створено;

stop;


@enduml
