@startuml EditAction


skinparam	shadowing false
skinparam Note {
	BackgroundColor #f85658
	FontColor #ffffff
}


|Модератор|
start
: Модератор обирає файл даних із тих,
які присутні в системі;

|Система|
: Повідомляє що файл знайдений і
готовий до видалення;

|Модератор|
: Модератор натискає 'видалити файл даних';

|Система|
: Система надсилає форму для підтвердження; 

|Модератор|
: Натискає 'так';

|Система|
: Видаляє обраний файл;

|Модератор|
: Отримує повідомлення, про те,
що файл був видалений;

stop;
@enduml
