@startuml
skinparam ArchimateBackgroundColor #ffffff
skinparam	shadowing false
skinparam Note {
	BackgroundColor #f85658
	FontColor #ffffff
}



|Модератор|
start
: Обирає набір даних;

|Система|
: Знаходить набір даних; 
: Повертає форму для додавання тегу;

|Модератор|
: Вводить тег;
: Натискає кнопку "Додати тег";

|Система|

: Додає тег;
note right
Можливо ЕХ 06MODER
end note

|Модератор|

: Отиримує повідомлення що тег доданий;

stop;


@enduml
