@startuml EditAction



skinparam	shadowing false
skinparam Note {
	BackgroundColor #f85658
	FontColor #ffffff
}



|Модератор|
start
: Обирає файл даних;
: Натискає 'відкрити на редагування';

|Система|
: Відкриває файл на редагування;

|Модератор|
: Вносить зміни;

|Система|
: Вносить зміни в обраний файл;

|Модератор|
: Натискає 'зберегти зміни';

|Система|
: Зберігає файл;
: Надсилає повідомлення, про те, що файл збережено;

|Модератор|
:Отримує повідомлення, про те, що файл збережено;



stop;
@enduml
