@startuml EditAction


skinparam	shadowing false
skinparam Note {
	BackgroundColor #f85658
	FontColor #ffffff
}


|Модератор|
start
: Модератор обирає файл даних;
: Модератор видаляє файл даних;

|Система|
:Видаляє обраний файл;

|Модератор|
: Отримує повідомлення, про те,
що файл був видалений;

stop;
@enduml
