@startuml EditAction


skinparam	shadowing false
skinparam Note {
	BackgroundColor #f85658
	FontColor #ffffff
}



|Модератор|
start
:Обирає файл даних;
:Додає файл даних;


|Система|
:Додає обраний файл даних;
note right
Можливо ЕХ 01MODER
end note
|Система|
:Надсилає повідомлення про те, що файл додано;

|Модератор|
:Отримує повідомлення про те, що файл додано;

stop;
@enduml
