@startuml
skinparam ArchimateBackgroundColor #ffffff
skinparam	shadowing false
skinparam Note {
	BackgroundColor #f85658
	FontColor #ffffff
}



|Модератор|
start
: Обирає коментар користувача, на який дасть відповідь;

: Вводить свою відповідь;

: Натискає кнопку "Додати коментар";

|Система|

: Додає відповідь;


|Модератор|

: Відповідь додано;

stop;


@enduml
