@startuml
skinparam ArchimateBackgroundColor #ffffff
skinparam	shadowing false
skinparam Note {
	BackgroundColor #f85658
	FontColor #ffffff
}



|Модератор|
start
: Обирає коментар користувача, на який дасть відповідь;

|Система|
: Повертає форму для додовання відповіді;

|Модератор|
: Вводить свою відповідь;

: Натискає кнопку "Додати коментар";

|Система|

: Додає відповідь;
: Повідомляє що відповідь додана;

|Модератор|

: Отримує повідомлення, що відповідь додана;

stop;


@enduml
