@startuml

    left header
        <font color=000 size=16><b>ID:</b> UC_8.2
        <font color=000 size=16><b>Назва:</b> Редагування облікового запису
        <font color=000 size=16><b>Учасники:</b> Користувач, Система
        <font color=000 size=16><b>Передумови:</b> Існування даного облікового запису
        <font color=000 size=16><b>Результат:</b> Зміни в обліковому записі
        <font color=000 size=16><b>Виключні ситуації:</b>
        <font color=000 size=16> EX_8.2.1 Введений e-mail вже присутній в системі
        <font color=000 size=16> EX_8.2.2 Введене ім'я користувача вже присутнє в системі

        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header
    
    |Користувач|
        start
        : Натискає на кнопку "Редагуваня акаунту";
    |Система|
        : Надає форму з інформацією для редагуваня;

    |Користувач|
        : Виконує зміни;
        : Натискає кнопку "Оновити акаунт";
        
    |Система|
        : Обробляє нові дані;
 
        note right #ffaaaa
        <b> Можливо
        <b> EX_8.2.1
        <b> EX_8.2.2
        end note

		: Вносить зміни в обліковий запис;

    |Користувач|
        stop;
    
@enduml
