@startuml

    left header
        <font color=000 size=16><b>ID:</b> UC_8.1
        <font color=000 size=16><b>Назва:</b> Видалення облікового запису
        <font color=000 size=16><b>Учасники:</b> Користувач, Система
        <font color=000 size=16><b>Передумови:</b> Існування даного облікового запису
        <font color=000 size=16><b>Результат:</b> Видалення облікового запису
        <font color=000 size=16><b>Виключні ситуації:</b>
        <font color=000 size=16> EX_8.1.1 Користувач не підтверджує видалення облікового запису

        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header
    
    |Користувач|
        start
        : Натискає на кнопку "Редагуваня акаунту";
    |Система|
        : Надає форму для редагуваня;

    |Користувач|
        : Натискає кнопку "Видалити акаунт";
        
    |Система|
        : Надсилає запит для підтвердження користувачу;
        
    |Користувач|
        : Натискає кнопку "Підтвердити";
        
        note left #ffaaaa
        <b> Можливо
        <b> EX_8.1.1
        end note
        
    |Система|
        : Обробляє запит;
        : Видаляє обліковий запис користувача;
        
    |Користувач|
        stop;
    
@enduml
