@startuml
    right header
        <font size=24 color=black>Package:<b> UCD_2.2
    end header

    package UCD_1.1 {
        usecase "<b>UC_3</b>\nКерувати категоріями" as UC_3 #aaeeaa
    }
    
    actor "Адміністратор" as Admin #eeee99
    Admin -l-> UC_3
    
    usecase "<b>UC_3.1</b>\nСтворити нову категорію" as UC_1.1
    usecase "<b>UC_3.2</b>\nВидалити існуючу категорію" as UC_1.2
    
    UC_1.1 .u.> UC_3: extends
    UC_1.2 .u.> UC_3: extends
    
@enduml
