@startuml
    right header
        <font size=24 color=black>Package:<b> UCD_2.3
    end header

    package UCD_1.1 {
        usecase "<b>UC_5</b>\nВзаємодія з набором даних" as UC_3 #aaeeaa
    }
    
    actor "Модератор" as Admin #eeee99
    Admin -l-> UC_3
    
    usecase "<b>UC_5.1</b>\nВидалити файл з набору даних" as UC_1.1
    usecase "<b>UC_5.2</b>\nДодати файли до набору даних" as UC_1.2
    usecase "<b>UC_5.3</b>\nРедагувати файл з набору даних" as UC_1.3
    
    UC_1.1 .u.> UC_3: extends
    UC_1.2 .u.> UC_3: extends
    UC_1.3 .u.> UC_3: extends
    
@enduml
