@startuml
right header
        <font size=24 color=black>Package: <b>UCD_1.1
    end header

actor :Адміністратор: as Admin
actor :Модератор: as Moder
actor :Користувач\n (не зареєстрований): as User
actor :Користувач\n (зареєстрований): as UserR
actor :Стороннє програмне забезпечення: as Prog

usecase "<b>UC_1</b>\nКерувати модераторами" as UC_1
usecase "<b>UC_2</b>\nКерувати доступом модераторів\n до набору даних" as UC_2
usecase "<b>UC_3</b>\nКерувати категоріями" as UC_3
usecase "<b>UC_4</b>\nКерувати наборами даних" as UC_4

usecase "<b>UC_5</b>\nВзаємодія з набором даних" as UC_5
usecase "<b>UC_6</b>\nВідповісти на коментар" as UC_6

usecase "<b>UC_7</b>\nСтворити коментар" as UC_7
usecase "<b>UC_8</b>\nКерувати обл. записом" as UC_8
usecase "<b>UC_9</b>\nВхід в систему" as UC_9

usecase "<b>UC_10</b>\nЗавантажити файл даних" as UC_10
usecase "<b>UC_11</b>\nСтворити обл. запис" as UC_11
usecase "<b>UC_12</b>\nПошук наборів даних" as UC_12

usecase "<b>UC_13</b>\nЗнайти та завантажити файл\n даних за допомогою API" as UC_13



Admin -right-|> Moder
Moder -right-|> UserR
UserR -right-|> User

Admin -up-> UC_1
Admin -up-> UC_2
Admin -down-> UC_3
Admin -down-> UC_4

Moder -up-> UC_5
Moder -down-> UC_6

UserR --> UC_7
UserR -up-> UC_8
UserR --> UC_9

User -up-> UC_10
User --> UC_11
User --> UC_12

Prog --> UC_13


    right footer
        Open data management system
        НТУУ КПІ ім.І.Сікорського
        Киів-2020
    end footer
@enduml
