@startuml
    right header
        <font size=24 color=black>Package:<b> UCD_2.4
    end header

    package UCD_1.1 {
        usecase "<b>UC_12</b>\nПереглянути файли даних" as UC_12 #aaeeaa
    }
    
    actor "Користувач" as User #eeee99
    User -l-> UC_12
    
    usecase "<b>UC_12.1</b>\nВикористати фільтри" as UC_12.1
    usecase "<b>UC_12.2</b>\nЗнайти файл вручну" as UC_12.2

    
    UC_12.1 .u.> UC_12: extends
    UC_12.2 .u.> UC_12: extends
@enduml
