@startuml
right header
        <font size=24 color=black>Package: <b>UCD_1.1
    end header

actor :Адміністратор: as Admin
actor :Модератор: as Moder
actor :Користувач: as User

usecase "<b>UC_1</b>\nКерувати доступом\n до наборів даних" as UC_1
usecase "<b>UC_2</b>\nКерувати модераторами" as UC_2

usecase "<b>UC_3</b>\nОперувати даними" as UC_3
usecase "<b>UC_4</b>\nРедагувати особисті дані" as UC_4

usecase "<b>UC_5</b>\nЗнайти набір даних" as UC_5
usecase "<b>UC_6</b>\nПереглянути загальну \nстатистику даних" as UC_6
usecase "<b>UC_7</b>\nЗавантажити набір даних" as UC_7

Admin -up-|> Moder
Moder -up-|> User

Admin --> UC_1
Admin --> UC_2

Moder -r-> UC_3
Moder -l-> UC_4

User -r-> UC_5
User -up-> UC_6
User -l-> UC_7

    right footer
        Open data management system
        НТУУ КПІ ім.І.Сікорського
        Киів-2020
    end footer
@enduml
