@startuml

    |Користувач|
        start
        : Натискає на кнопку "Залишити коментар";
        
    |Система|
        : Надає поле для запису коментара;

    |Користувач|
        : Вводить коментар;
        
    |Система|
        : Перевіряє коментар;
        
        note right #ffaaaa
        <b> Можливо
        <b> EX_7.1
        <b> EX_7.2
        end note
        
        : Створює коментар та асоціює його
         з відповідним набором даних;
		
    |Користувач|
        stop;
    
@enduml
