@startuml

    left header
        <font color=000 size=16><b>ID:</b> UC_9
        <font color=000 size=16><b>Назва:</b> Створення коментаря
        <font color=000 size=16><b>Учасники:</b> Користувач, Система
        <font color=000 size=16><b>Передумови:</b> В системі присутній набір даних до якого буде створюватися коментар,
        <font color=000 size=16> користувач авторизований в системі
        <font color=000 size=16><b>Результат:</b> Коментар створено
        <font color=000 size=16><b>Виключні ситуації:</b>
        <font color=000 size=16> EX_9.1 Коментар не може бути пустим
        <font color=000 size=16> EX_9.2 Коментар не може бути довшим ніж 999 символів

        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header
    
    |Користувач|
        start
        : Натискає на кнопку "Залишити коментар";
        
    |Система|
        : Надає поле для запису коментара;

    |Користувач|
        : Вводить коментар;
        
    |Система|
        : Обробляє коментар;
        
        note right #ffaaaa
        <b> Можливо
        <b> EX_9.1
        <b> EX_9.2
        end note
        
		: Завантажує коментар;
		
    |Користувач|
        stop;
    
@enduml
