@startuml

    |Користувач|
        start
        : Вибирає потрібний набір даних;
        : Натискає на кнопку "Завантажити";
        
    |Система|
        : Шукає відповідний файл в системі
         й перевіряє доступ до нього;
        
         note right #ffaaaa
        <b> Можливо
        <b> EX_10.1
        end note
        
        : Дає доступ до завантаження;

        note right #ffaaaa
        <b> Можливо
        <b> EX_10.2
        end note
    	
    |Користувач|
        stop;
    
@enduml
