@startuml
    
    |Користувач|
        start
        : Натискає на кнопку "Реєстрація";
    |Система|
        : Надає форму для реєстрації;

    |Користувач|
        : Вводить ім'я користувача, логін, e-mail, пароль;
        
        : Натискає кнопку "Створити акаунт";
        
    |Система|
        : Перевіряє введені дані;
        note right #ffaaaa
        <b> Можливо
        <b> EX_11.1
        <b> EX_11.2
        <b> EX_11.3
        <b> EX_11.4
        <b> EX_11.5
        end note
        
	: Створює обліковий запис користувача;
		
    |Користувач|
        stop;
    
@enduml
