@startuml

    left header
        <font color=000 size=16><b>ID:</b> UC_11
        <font color=000 size=16><b>Назва:</b> Вхід в систему
        <font color=000 size=16><b>Учасники:</b> Користувач, Система
        <font color=000 size=16><b>Передумови:</b> Існування облікового запису
        <font color=000 size=16><b>Результат:</b> Вхід в систему
        <font color=000 size=16><b>Виключні ситуації:</b>
        <font color=000 size=16> EX_11.1 Некоректний e-mail чи пароль

        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header
    
    |Користувач|
        start
        : Натискає на кнопку "Уввійти";
    |Система|
        : Надає форму для входу в систему;

    |Користувач|
        : Вводить e-mail та пароль;
        : Натискає кнопку "Вхід";
        
    |Система|
        : Обробляє форму;
 
        note right #ffaaaa
        <b> Можливо
        <b> EX_11.1
        end note

        : Здійснює вхід користувача в систему;

    |Користувач|
        stop;
    
@enduml
