@startuml

    |Користувач|
        start
        : Натискає на кнопку "Редагуваня акаунту";
    |Система|
        : Надає форму для редагуваня;

    |Користувач|
        : Натискає кнопку "Видалити акаунт";
        
    |Система|
        : Надсилає запит для підтвердження користувачу;
        
    |Користувач|
        : Натискає кнопку "Підтвердити";
        
        note left #ffaaaa
        <b> Можливо
        <b> EX_8.1.1
        end note
        
    |Система|
        : Видаляє обліковий запис користувача;
        
    |Користувач|
        stop;
    
@enduml
