@startuml

    left header
        <font color=000 size=16><b>ID:</b> UC_6
        <font color=000 size=16><b>Назва:</b> Завантаження файлів з набору даних
        <font color=000 size=16><b>Учасники:</b> Користувач, Система
        <font color=000 size=16><b>Передумови:</b> В системі присутній набір даних, з якого будуть завантажувати файли
        <font color=000 size=16><b>Результат:</b> Завантажені файли
        <font color=000 size=16><b>Виключні ситуації:</b>
        <font color=000 size=16> EX_6.1 Користувач не підтверджує завантаження
        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header
    
    |Користувач|
        start
        : Вибирає потрібний набір даних;
        : Натискає на кнопку "Завантажити";
        
    |Система|
        : Обробляє запит;
        : Дає доступ до завантаження;

        note right #ffaaaa
        <b> Можливо
        <b> EX_6.1
        end note
    	
    |Користувач|
        stop;
    
@enduml
