@startuml

    |Користувач|
        start
        : Натискає на кнопку "Уввійти";
    |Система|
        : Надає форму для входу в систему;

    |Користувач|
        : Вводить e-mail та пароль;
        : Натискає кнопку "Вхід";
        
    |Система|
        : Перевіряє введені дані;
 
        note right #ffaaaa
        <b> Можливо
        <b> EX_9.1
        end note

        : Здійснює вхід користувача в систему;

    |Користувач|
        stop;
    
@enduml
